# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-17 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('receiver', models.CharField(max_length=10, verbose_name='收件人')),
                ('address', models.CharField(max_length=100, verbose_name='用户地址')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否删除')),
                ('postcode', models.CharField(max_length=7, verbose_name='邮政编码')),
                ('receiver_mobile', models.CharField(max_length=11, verbose_name='电话')),
                ('tag', models.CharField(default=None, max_length=10, verbose_name='标签')),
            ],
            options={
                'verbose_name': '用户地址',
                'verbose_name_plural': '用户地址',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.CharField(max_length=11, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=11, verbose_name='手机')),
                ('is_active', models.BooleanField(default=False, verbose_name='激活状态')),
            ],
            options={
                'db_table': 'user_user_profile',
            },
        ),
        migrations.CreateModel(
            name='WeiboProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('wuid', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='微博uid')),
                ('access_token', models.CharField(db_index=True, max_length=32, verbose_name='微博授权令牌')),
                ('user_profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
            options={
                'verbose_name': '微博用户表',
                'verbose_name_plural': '微博用户表',
                'db_table': 'user_weibo_profile',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile', verbose_name='用户id'),
        ),
    ]
