# Generated by Django 2.2.12 on 2020-06-09 11:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeckillMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='VIP月数')),
                ('count', models.IntegerField(verbose_name='秒杀数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='价格')),
                ('begin_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开启时间')),
                ('continue_time', models.IntegerField(verbose_name='持续时间(s)')),
                ('sell_out_time', models.IntegerField(default=99999, verbose_name='售罄时间')),
                ('surplus_count', models.IntegerField(default=-1, verbose_name='剩余数量')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'seckill_message',
            },
        ),
        migrations.CreateModel(
            name='SeckillBehavior',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='时间戳')),
                ('label', models.CharField(max_length=3, verbose_name='标签')),
                ('count', models.IntegerField(verbose_name='尝试抢购次数')),
                ('surplus_vip_time', models.IntegerField(verbose_name='参与秒杀时，用户剩余VIP天数')),
                ('seckill_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seckills.SeckillMessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.Users')),
            ],
            options={
                'db_table': 'seckill_behavior',
            },
        ),
    ]
