# Generated by Django 2.2.12 on 2020-05-31 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'user_user_profile',
            },
        ),
        migrations.CreateModel(
            name='WeiboProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wuid', models.CharField(max_length=10, unique=True, verbose_name='微博uid')),
                ('access_token', models.CharField(max_length=32, verbose_name='权限令牌')),
                ('user_profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
            options={
                'db_table': 'user_weibo_profile',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=10, verbose_name='收件人')),
                ('address', models.CharField(max_length=100, verbose_name='用户地址')),
                ('postcode', models.CharField(max_length=6, verbose_name='邮编')),
                ('receiver_mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('tag', models.CharField(max_length=10, verbose_name='标签')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为默认地址')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
        ),
    ]
