# Generated by Django 2.2.12 on 2020-06-09 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Name', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('user_Email', models.EmailField(max_length=30, verbose_name='邮箱')),
                ('vip', models.DateTimeField(auto_now_add=True, verbose_name='VIP有效期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否存在')),
                ('user_created_Time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user_updated_Time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_Name', models.CharField(max_length=30, unique=True, verbose_name='昵称')),
                ('user_Type', models.CharField(max_length=30, verbose_name='用户类型')),
                ('career', models.CharField(max_length=30, verbose_name='职业')),
                ('user_Addr', models.CharField(max_length=100, verbose_name='用户地址')),
                ('gender', models.BooleanField(null=True, verbose_name='性别')),
                ('birth', models.DateField(auto_now_add=True, verbose_name='生日')),
                ('portrait', models.ImageField(null=True, upload_to='', verbose_name='头像')),
                ('profile_created_Time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('profile_updated_Time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Users')),
            ],
        ),
        migrations.CreateModel(
            name='User_Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderator_id', models.CharField(max_length=30, null=True, unique=True, verbose_name='吧主编号')),
                ('administrater_id', models.CharField(max_length=30, null=True, unique=True, verbose_name='管理员编号')),
                ('administrater_Group', models.CharField(max_length=30, verbose_name='所属管理员分组')),
                ('id_created_Time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('id_updated_Time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Users')),
            ],
        ),
    ]
